collection: page
slug: home
meta:
  description: Webseite im Aufbau...
  title: AHS Oberland GmbH
  image: ""
header:
  image: ../media/test.png
  title: Vielen Dank für Ihren Besuch
  text: Derzeit befindet sich unsere Webseite im Aufbau.
jobs:
  title: Jobs - Wir suchen aktuell
